### ISSUE TITLE
Minor version ignored?

### ISSUE THREAD

**Issue by elpatron68** [gup4win/wingup#17]
Hi,

If I define

```
$lastestVersion = 1.5; // X.YZ
$lastestVersionStr = "1.5.6"; // X.Y.Z
```
in `getDownLoadUrl.php` and my application sends it's version string as `1.5.4`, there will be not update offended. `$lastestVersionStr` seems not to be relevant for the version check? Or how can I define minor versions in `$lastestVersion`?

Best regards,
Markus

**Comment by donho** [comment]
@elpatron68 
With the way of managing the version comparison in provided `getDownLoadUrl.php`, your application should send 1.54 instead of "1.5.4".
The provided  `getDownLoadUrl.php` may not perfect for the version comparison but you can do your php file (or in other language, depends on your server) for your application being able to send the version format you want.

**Comment by elpatron68** [comment]
Thanks for helping!
